# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('uk_organisation', models.BooleanField(default=True)),
                ('country', models.CharField(choices=[('United Kingdom', '80756b9a-5d95-e211-a939-e4115bead28a')], max_length=255)),
                ('postcode', models.CharField(max_length=255)),
                ('address1', models.CharField(max_length=255)),
                ('uk_region', models.CharField(choices=[('London', '874cd12a-6095-e211-a939-e4115bead28a')], max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('area_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('Food & Drink', 'a538cecc-5f95-e211-a939-e4115bead28a')], max_length=255)),
                ('cdms_pk', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
