# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_auto_20160202_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='city',
            field=models.CharField(default='london', max_length=255),
            preserve_default=False,
        ),
    ]
