# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_organisation_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
