# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:38
from __future__ import unicode_literals

import core.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=core.fields.UKTIForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Organisation'),
        ),
    ]
