# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 14:05
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0007_auto_20160216_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created',
            field=core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='modified',
            field=core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='created',
            field=core.fields.AutoCreatedField(default=core.fields.now_without_millisecs, editable=False),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='modified',
            field=core.fields.AutoLastModifiedField(default=core.fields.now_without_millisecs, editable=False),
        ),
    ]
